name: prowlarr-dotnet # you probably want to 'snapcraft register <name>'
summary: Prowlarr is an index manager for all the *arr apps # 79 char long summary
description: |
  Prowlarr is an indexer manager/proxy built on the popular *arr 
  .net/reactjs base stack to integrate with your various PVR apps. 
  Prowlarr supports management of both Torrent Trackers and Usenet Indexers. 
  It integrates seamlessly with Lidarr, Mylar3, Radarr, Readarr, and Sonarr 
  offering complete management of your indexers with no per app Indexer 
  setup required (we do it all).

  The web interface is accessible by default at http://localhost:9696

  See https://prowlarr.com for more details.

confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0+
icon: icon.svg
base: core20
grade: stable
adopt-info: set-version

package-repositories:
  - type: apt
    url: https://packages.microsoft.com/ubuntu/20.04/prod
    components: [main]
    suites: [focal]
    key-id: BC528686B50D79E339D3721CEB3E94ADBE1229CF

apps:
  prowlarr:
    command: bin/run-prowlarr
    daemon: simple
    plugs:
      - home
      - mount-observe
      - network
      - network-bind
      - removable-media
    stop-timeout: 30s

parts:

  local:
    plugin: dump
    source: snap/local

  set-version:
    plugin: nil
    override-pull:
      curl -sLG "https://prowlarr.servarr.com/v1/update/develop/changes?os=linux&runtime=netcore&arch=x64" --output changes.json
    override-build: |
      snapcraftctl set-version "$(jq -r .[0].version changes.json)"
    build-packages:
      - curl
      - jq

  prowlarr:
    plugin: nil
    source: 'https://prowlarr.servarr.com/v1/update/develop/updatefile?os=linux&runtime=netcore&arch=x64'
    source-type: tar
    override-build: |
      INST_DIR="$SNAPCRAFT_PART_INSTALL/prowlarr-dotnet"
      mkdir -p "$INST_DIR"
      cp -a * "$INST_DIR"

  deps:
    plugin: dump
    source: .
    stage-packages:
      - curl
      - mediainfo
      - sqlite3
      - apt-transport-https
      - dotnet-sdk-6.0
    filesets:
      bins:
        - usr/bin/sqlite*
      libs:
        - usr/lib
    stage:
      - $bins
      - $libs

